# Handling the missing values

In [5]:
import pandas as pd 
import numpy as np 
dataset = {
    'First' : ['corey' , 'Jane' , 'John' , 'Chris' , np.nan , None , np.nan],
    'Last' : ['schafer' , 'Doe' , 'Doe' , 'schafer' , np.nan ,np.nan , 'Missing'],
    'age' : ['33','55','63','36',None, None,'Missing']
}

df = pd.DataFrame(dataset)
display(df)

   First     Last      age
0  corey  schafer       33
1   Jane      Doe       55
2   John      Doe       63
3  Chris  schafer       36
4    NaN      NaN      NaN
5    NaN      NaN      NaN
6    NaN  Missing  Missing

In [6]:
df.dropna()  # --> drop columns that contain the missing values like NaN or None

   First     Last age
0  corey  schafer  33
1   Jane      Doe  55
2   John      Doe  63
3  Chris  schafer  36

In [ ]:
df.dropna(axis="index" , how="any") # --> set to 'any' >> drops if any value missing

   First     Last age
0  corey  schafer  33
1   Jane      Doe  55
2   John      Doe  63
3  Chris  schafer  36

In [ ]:
df.dropna(axis="index" , how="all") # --> set to 'all' >> drops every row or column having all missing value

   First     Last      age
0  corey  schafer       33
1   Jane      Doe       55
2   John      Doe       63
3  Chris  schafer       36
6    NaN  Missing  Missing

In [ ]:
df.dropna(axis='index' , how='any' , subset=['Last']) # --> subset >> allow to target specific column

   First     Last      age
0  corey  schafer       33
1   Jane      Doe       55
2   John      Doe       63
3  Chris  schafer       36
6    NaN  Missing  Missing

# Filling missing values

In [ ]:
df.isna() # --> returns boolean showing walue treated as missing

   First   Last    age
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4   True   True   True
5   True   True   True
6   True  False  False

In [ ]:
df.fillna('Missing') # --> replace NaN with any string value

     First     Last      age
0    corey  schafer       33
1     Jane      Doe       55
2     John      Doe       63
3    Chris  schafer       36
4  Missing  Missing  Missing
5  Missing  Missing  Missing
6  Missing  Missing  Missing

# Casting Datatypes

In [13]:
df.dtypes

First    str
Last     str
age      str
dtype: object