# Columns property

In [10]:
import pandas as pd 
df = pd.read_csv('ai_student_impact_dataset (1).csv')
display(df)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [11]:
df.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='str')

In [12]:
df.columns[0]

'Student_ID'

In [13]:
df.columns[0:10]

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours'],
      dtype='str')

In [15]:
df.columns.shape

(16,)

In [17]:
df['Student_ID']

0        100001
1        100002
2        100003
3        100004
4        100005
          ...
49995    149996
49996    149997
49997    149998
49998    149999
49999    150000
Name: Student_ID, Length: 50000, dtype: int64

In [19]:
df[['Student_ID', 'Major_Category']]

       Student_ID Major_Category
0          100001     Humanities
1          100002        Medical
2          100003       Business
3          100004       Business
4          100005           STEM
...           ...            ...
49995      149996       Business
49996      149997           STEM
49997      149998       Business
49998      149999       Business
49999      150000           Arts

[50000 rows x 2 columns]

# loc and iloc

In [ ]:
df.loc[0:100,["Student_ID",'Major_Category', 'Year_of_Study']] # --> Takes input as Label base

     Student_ID Major_Category Year_of_Study
0        100001     Humanities        Senior
1        100002        Medical        Junior
2        100003       Business      Freshman
3        100004       Business        Senior
4        100005           STEM     Sophomore
..          ...            ...           ...
96       100097       Business      Freshman
97       100098     Humanities      Graduate
98       100099           STEM      Freshman
99       100100           STEM      Graduate
100      100101           STEM     Sophomore

[101 rows x 3 columns]

In [29]:
df.loc[0:2]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium

In [30]:
df.loc[0]

Student_ID                                   100001
Major_Category                           Humanities
Year_of_Study                                Senior
Pre_Semester_GPA                              2.418
Weekly_GenAI_Hours                            23.31
Primary_Use_Case               Copywriting/Drafting
Prompt_Engineering_Skill                   Beginner
Tool_Diversity                                    1
Paid_Subscription                              True
Traditional_Study_Hours                        8.13
Perceived_AI_Dependency                           5
Institutional_Policy          Allowed_With_Citation
Anxiety_Level_During_Exams                        6
Post_Semester_GPA                             2.393
Skill_Retention_Score                         86.44
Burnout_Risk_Level                             High
Name: 0, dtype: object

In [ ]:
df.iloc[0:100,2:4] # --> Take input as integer based

   Year_of_Study  Pre_Semester_GPA
0         Senior             2.418
1         Junior             3.821
2       Freshman             3.398
3         Senior             3.789
4      Sophomore             3.635
..           ...               ...
95        Senior             3.773
96      Freshman             2.907
97      Graduate             2.292
98      Freshman             2.016
99      Graduate             2.661

[100 rows x 2 columns]

In [33]:
df.iloc[0]

Student_ID                                   100001
Major_Category                           Humanities
Year_of_Study                                Senior
Pre_Semester_GPA                              2.418
Weekly_GenAI_Hours                            23.31
Primary_Use_Case               Copywriting/Drafting
Prompt_Engineering_Skill                   Beginner
Tool_Diversity                                    1
Paid_Subscription                              True
Traditional_Study_Hours                        8.13
Perceived_AI_Dependency                           5
Institutional_Policy          Allowed_With_Citation
Anxiety_Level_During_Exams                        6
Post_Semester_GPA                             2.393
Skill_Retention_Score                         86.44
Burnout_Risk_Level                             High
Name: 0, dtype: object