# Filter in Pandas

In [1]:
import pandas as pd
df = pd.read_csv("ai_student_impact_dataset (1).csv")
df

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [ ]:
cgpa = df['Major_Category'] == "Business"
df[cgpa]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
9,100010,Business,Sophomore,3.046,19.99,Debugging/Troubleshooting,Intermediate,2,True,12.49,3,Strict_Ban,8,2.978,87.18,High
17,100018,Business,Senior,3.156,8.03,Direct_Answer_Generation,Advanced,4,False,10.70,4,Allowed_With_Citation,5,3.390,90.65,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49990,149991,Business,Senior,2.970,2.63,Summarizing_Reading,Intermediate,2,False,24.95,1,Allowed_With_Citation,1,3.238,84.87,Medium
49992,149993,Business,Graduate,2.829,2.59,Debugging/Troubleshooting,Advanced,3,True,7.54,1,Allowed_With_Citation,4,3.176,84.04,Low
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium

In [30]:
filt2 = df["Student_ID"] >= 149991
df.loc[filt2,"Year_of_Study"]

49990       Senior
49991     Freshman
49992     Graduate
49993    Sophomore
49994       Senior
49995       Senior
49996       Senior
49997       Senior
49998       Junior
49999    Sophomore
Name: Year_of_Study, dtype: str

In [50]:
skill = ['Intermediate' , "Advanced"]
data = df["Prompt_Engineering_Skill"].isin(skill)
display(df.loc[data, ["Student_ID"]])

       Student_ID
1          100002
3          100004
4          100005
6          100007
7          100008
...           ...
49993      149994
49994      149995
49996      149997
49997      149998
49998      149999

[31505 rows x 1 columns]

# Logical operator

In [32]:
filt2 = (df["Student_ID"] >= 145731 ) & (df['Major_Category'] == "Business")
df.loc[filt2,["Year_of_Study","Primary_Use_Case"]]

      Year_of_Study           Primary_Use_Case
45730     Sophomore   Direct_Answer_Generation
45731      Freshman        Summarizing_Reading
45739      Freshman                   Ideation
45746        Senior  Debugging/Troubleshooting
45748        Junior       Copywriting/Drafting
...             ...                        ...
49990        Senior        Summarizing_Reading
49992      Graduate  Debugging/Troubleshooting
49995        Senior       Copywriting/Drafting
49997        Senior        Summarizing_Reading
49998        Junior  Debugging/Troubleshooting

[1054 rows x 2 columns]

In [33]:
filt2 = (df["Student_ID"] >= 145731 ) & (df['Major_Category'] == "Business") | (df['Prompt_Engineering_Skill'] == "Advanced")
df.loc[filt2,["Year_of_Study","Primary_Use_Case"]]

      Year_of_Study           Primary_Use_Case
1            Junior                   Ideation
4         Sophomore  Debugging/Troubleshooting
6          Freshman        Summarizing_Reading
10         Graduate        Summarizing_Reading
16        Sophomore   Direct_Answer_Generation
...             ...                        ...
49992      Graduate  Debugging/Troubleshooting
49994        Senior        Summarizing_Reading
49995        Senior       Copywriting/Drafting
49997        Senior        Summarizing_Reading
49998        Junior  Debugging/Troubleshooting

[14619 rows x 2 columns]

In [ ]:
filt2 = ~ ((df["Student_ID"] >= 145731 ) & (df['Major_Category'] == "Business") | (df['Prompt_Engineering_Skill'] == "Advanced"))
df.loc[filt2,["Year_of_Study","Primary_Use_Case"]]

      Year_of_Study           Primary_Use_Case
0            Senior       Copywriting/Drafting
2          Freshman        Summarizing_Reading
3            Senior       Copywriting/Drafting
5            Junior  Debugging/Troubleshooting
7            Junior       Copywriting/Drafting
...             ...                        ...
49988     Sophomore  Debugging/Troubleshooting
49991      Freshman       Copywriting/Drafting
49993     Sophomore  Debugging/Troubleshooting
49996        Senior       Copywriting/Drafting
49999     Sophomore       Copywriting/Drafting

[35381 rows x 2 columns]