# Updating columns names

In [15]:
import pandas as pd
df = pd.read_csv("ai_student_impact_dataset (1).csv", index_col='Student_ID')
df

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Student_ID,,,,,,,,,,,,,,,
100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [16]:
df.columns=['experience'] # --> Gives error; use this when u want to change all column names otherwise use rename() method

ValueError: Length mismatch: Expected axis has 15 elements, new values have 1 elements

In [ ]:
df.rename(columns = {
    'Year_of_Study': 'Experience',
    'Major_Category' : 'Field_of_study',
    'Weekly_GenAI_Hours' : 'Weekly_GenAI_Usage'
})                                                  # --> Column name changed

,Field_of_study,Experience,Pre_Semester_GPA,Weekly_GenAI_Usage,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Student_ID,,,,,,,,,,,,,,,
100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [ ]:
df.columns =[x.upper() for x in df.columns] # --> Applying function on the columns
df

,MAJOR_CATEGORY,YEAR_OF_STUDY,PRE_SEMESTER_GPA,WEEKLY_GENAI_HOURS,PRIMARY_USE_CASE,PROMPT_ENGINEERING_SKILL,TOOL_DIVERSITY,PAID_SUBSCRIPTION,TRADITIONAL_STUDY_HOURS,PERCEIVED_AI_DEPENDENCY,INSTITUTIONAL_POLICY,ANXIETY_LEVEL_DURING_EXAMS,POST_SEMESTER_GPA,SKILL_RETENTION_SCORE,BURNOUT_RISK_LEVEL
Student_ID,,,,,,,,,,,,,,,
100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

# Updating Rows

In [ ]:
df.loc[100001] = ['Arts' , 'Fresher' , 3.146 , 24.65 , 'Debugging/Troubleshooting' , 'Beginner' , 2 , False , 4.56 , 6 , 'Allowed_With_Citation' , 5 , 2.393 , 86.44 , 'Low' ] # ---> row changed
 
df

,MAJOR_CATEGORY,YEAR_OF_STUDY,PRE_SEMESTER_GPA,WEEKLY_GENAI_HOURS,PRIMARY_USE_CASE,PROMPT_ENGINEERING_SKILL,TOOL_DIVERSITY,PAID_SUBSCRIPTION,TRADITIONAL_STUDY_HOURS,PERCEIVED_AI_DEPENDENCY,INSTITUTIONAL_POLICY,ANXIETY_LEVEL_DURING_EXAMS,POST_SEMESTER_GPA,SKILL_RETENTION_SCORE,BURNOUT_RISK_LEVEL
Student_ID,,,,,,,,,,,,,,,
100001,Arts,Fresher,3.146,24.65,Debugging/Troubleshooting,Beginner,2,False,4.56,6,Allowed_With_Citation,5,2.393,86.44,Low
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [ ]:
df.loc[100001,'MAJOR_CATEGORY'] = ['STEM'] # --> Row of specific column changed
display(df)

,MAJOR_CATEGORY,YEAR_OF_STUDY,PRE_SEMESTER_GPA,WEEKLY_GENAI_HOURS,PRIMARY_USE_CASE,PROMPT_ENGINEERING_SKILL,TOOL_DIVERSITY,PAID_SUBSCRIPTION,TRADITIONAL_STUDY_HOURS,PERCEIVED_AI_DEPENDENCY,INSTITUTIONAL_POLICY,ANXIETY_LEVEL_DURING_EXAMS,POST_SEMESTER_GPA,SKILL_RETENTION_SCORE,BURNOUT_RISK_LEVEL
Student_ID,,,,,,,,,,,,,,,
100001,STEM,Fresher,3.146,24.65,Debugging/Troubleshooting,Beginner,2,False,4.56,6,Allowed_With_Citation,5,2.393,86.44,Low
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [ ]:
df.at[100002,'Major_Category'] = ['Arts']
display(df)

,MAJOR_CATEGORY,YEAR_OF_STUDY,PRE_SEMESTER_GPA,WEEKLY_GENAI_HOURS,PRIMARY_USE_CASE,PROMPT_ENGINEERING_SKILL,TOOL_DIVERSITY,PAID_SUBSCRIPTION,TRADITIONAL_STUDY_HOURS,PERCEIVED_AI_DEPENDENCY,INSTITUTIONAL_POLICY,ANXIETY_LEVEL_DURING_EXAMS,POST_SEMESTER_GPA,SKILL_RETENTION_SCORE,BURNOUT_RISK_LEVEL,Major_Category
Student_ID,,,,,,,,,,,,,,,,
100001,STEM,Fresher,3.146,24.65,Debugging/Troubleshooting,Beginner,2,False,4.56,6,Allowed_With_Citation,5,2.393,86.44,Low,nan
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low,Arts
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium,nan
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium,nan
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High,nan
149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium,nan
149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High,nan
149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium,nan
150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low,nan

In [ ]:

def Update_Burnout_Risk_Level(BURNOUT_RISK_LEVEL):
    return BURNOUT_RISK_LEVEL.upper()

df['BURNOUT_RISK_LEVEL'].apply(Update_Burnout_Risk_Level)   # --> Using apply() method on dataframe

Student_ID
100001       LOW
100002       LOW
100003    MEDIUM
100004    MEDIUM
100005    MEDIUM
           ...
149996      HIGH
149997    MEDIUM
149998      HIGH
149999    MEDIUM
150000       LOW
Name: BURNOUT_RISK_LEVEL, Length: 50000, dtype: str

In [ ]:
df.select_dtypes(include=['object','str']).map(len) # --> Using .map() method on dataframe

,Major_Category,Year_of_Study,Primary_Use_Case,Prompt_Engineering_Skill,Institutional_Policy,Burnout_Risk_Level
Student_ID,,,,,,
100001,10,6,20,8,21,4
100002,7,6,8,8,21,3
100003,8,8,19,8,10,6
100004,8,6,20,12,21,6
100005,4,9,25,8,21,6
...,...,...,...,...,...,...
149996,8,6,20,8,21,4
149997,4,6,20,12,19,6
149998,8,6,19,8,21,4
149999,8,6,25,12,21,6
150000,4,9,20,8,21,3